version: '2'
services:
  app:
    image: ruby:2.4
    working_dir: /workdir
    environment:
      BUNDLE_PATH: /workdir/.bundle
    command: ruby app.rb
    volumes:
      - .:/workdir
    ports:
      - "4567:4567"
